// this is generated by Gcode-Plot.py
// These values are in angles from a minimum of -30
// to a maximum of +30 degrees plot function will take care of
// the Q values
#define NVALS 19
const int32_t xPlots[NVALS] = { 0, 5, 10, 5, 10, 15, 10, 15, 20, 0, -20, -15,
                                -10, -15, -10, -5, -10, -5, 0 };
const int32_t yPlots[NVALS] = { 15, 10, 5, 5, 0, -5, -5, -10, -15, -15, -15,
                                -10, -5, -5, 0, 5, 5, 10, 15 };
