#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C28_large{1,0,6.2,0
#
task.x28L: package/cfg/task.x28L.mak

clean::
	-$(RM) package/cfg/task.x28L.mak
